tinymce.addI18n('id',{
"Cut": "Penggal",
"Heading 5": "Judul 5",
"Header 2": "Header 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Browser anda tidak mendukung akses langsung ke clipboard. Silahkan gunakan Ctrl+X\/C\/V dari keyboard.",
"Heading 4": "Judul 4",
"Div": "Div",
"Heading 2": "Judul 2",
"Paste": "Tempel",
"Close": "Tutup",
"Font Family": "Jenis Huruf",
"Pre": "Pre",
"Align right": "Rata kanan",
"New document": "Dokumen baru",
"Blockquote": "Kutipan",
"Numbered list": "List Angka",
"Heading 1": "Judul 1",
"Headings": "Judul",
"Increase indent": "Tambah inden",
"Formats": "Format",
"Headers": "Header",
"Select all": "Pilih semua",
"Header 3": "Header 3",
"Blocks": "Blok",
"Undo": "Batal",
"Strikethrough": "Coret",
"Bullet list": "List Simbol",
"Header 1": "Header 1",
"Superscript": "Superskrip",
"Clear formatting": "Hapus format",
"Font Sizes": "Ukuran Huruf",
"Subscript": "Subskrip",
"Header 6": "Header 6",
"Redo": "Ulang",
"Paragraph": "Paragraf",
"Ok": "Ok",
"Bold": "Tebal",
"Code": "Code",
"Italic": "Miring",
"Align center": "Rate tengah",
"Header 5": "Header 5",
"Heading 6": "Judul 6",
"Heading 3": "Judul 3",
"Decrease indent": "Turunkan inden",
"Header 4": "Header 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.",
"Underline": "Garis bawah",
"Cancel": "Batal",
"Justify": "Rata kanan-kiri",
"Inline": "Inline",
"Copy": "Salin",
"Align left": "Rate kiri",
"Visual aids": "Alat bantu visual",
"Lower Greek": "Lower Yunani",
"Square": "Kotak",
"Default": "Bawaan",
"Lower Alpha": "Lower Alpha",
"Circle": "Lingkaran",
"Disc": "Cakram",
"Upper Alpha": "Upper Alpha",
"Upper Roman": "Upper Roman",
"Lower Roman": "Lower Roman",
"Name": "Nama",
"Anchor": "Anjar",
"You have unsaved changes are you sure you want to navigate away?": "Anda memiliki perubahan yang belum disimpan, yakin ingin beralih ?",
"Restore last draft": "Muat kembali draft sebelumnya",
"Special character": "Karakter Khusus",
"Source code": "Kode sumber",
"Right to left": "Kanan ke kiri",
"Left to right": "Kiri ke kanan",
"Emoticons": "Emotikon",
"Robots": "Robot",
"Document properties": "Properti dokumwn",
"Title": "Judul",
"Keywords": "Kata kunci",
"Encoding": "Enkoding",
"Description": "Description",
"Author": "Penulis",
"Fullscreen": "Layar penuh",
"Horizontal line": "Horizontal line",
"Horizontal space": "Horizontal space",
"Insert\/edit image": "Insert\/edit image",
"General": "General",
"Advanced": "Advanced",
"Source": "Source",
"Border": "Border",
"Constrain proportions": "Constrain proportions",
"Vertical space": "Vertical space",
"Image description": "Image description",
"Style": "Style",
"Dimensions": "Dimensions",
"Insert image": "Insert image",
"Insert date\/time": "Insert date\/time",
"Remove link": "Hapus Link",
"Url": "Url",
"Text to display": "Text to display",
"Anchors": "Anchors",
"Insert link": "Masukkan Link",
"New window": "New window",
"None": "None",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?",
"Target": "Target",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?",
"Insert\/edit link": "Masukkan\/edit link",
"Insert\/edit video": "Insert\/edit video",
"Poster": "Poster",
"Alternative source": "Alternative source",
"Paste your embed code below:": "Paste your embed code below:",
"Insert video": "Insert video",
"Embed": "Embed",
"Nonbreaking space": "Nonbreaking space",
"Page break": "Page break",
"Paste as text": "Paste as text",
"Preview": "Preview",
"Print": "Print",
"Save": "Save",
"Could not find the specified string.": "Could not find the specified string.",
"Replace": "Replace",
"Next": "Next",
"Whole words": "Whole words",
"Find and replace": "Find and replace",
"Replace with": "Replace with",
"Find": "Find",
"Replace all": "Replace all",
"Match case": "Match case",
"Prev": "Prev",
"Spellcheck": "Spellcheck",
"Finish": "Finish",
"Ignore all": "Ignore all",
"Ignore": "Ignore",
"Insert row before": "Masukkan baris ke sebelumnya",
"Rows": "Rows",
"Height": "Height",
"Paste row after": "Tempel Baris Ke Setelahnya",
"Alignment": "Alignment",
"Column group": "Column group",
"Row": "Row",
"Insert column before": "Masukkan Kolom Ke Sebelumnya",
"Split cell": "Split cell",
"Cell padding": "Cell padding",
"Cell spacing": "Cell spacing",
"Row type": "Row type",
"Insert table": "Buat Tabel",
"Body": "Body",
"Caption": "Caption",
"Footer": "Footer",
"Delete row": "Hapus Baris",
"Paste row before": "Tempel Baris Ke Setelahnya",
"Scope": "Scope",
"Delete table": "Hapus Tabel",
"Header cell": "Header cell",
"Column": "Kolom",
"Cell": "Cell",
"Header": "Header",
"Cell type": "Cell type",
"Copy row": "Salin Baris",
"Row properties": "Properti Baris",
"Table properties": "Properti Tabel",
"Row group": "Baris Grup",
"Right": "Right",
"Insert column after": "Masukkan Kolom Ke Setelahnya",
"Cols": "Cols",
"Insert row after": "Masukkan baris ke setelahnya",
"Width": "Width",
"Cell properties": "Cell properties",
"Left": "Left",
"Cut row": "Potong Baris",
"Delete column": "Hapus Kolom",
"Center": "Center",
"Merge cells": "Merge cells",
"Insert template": "Insert template",
"Templates": "Templates",
"Background color": "Background color",
"Text color": "Warna Text",
"Show blocks": "Show blocks",
"Show invisible characters": "Show invisible characters",
"Words: {0}": "Words: {0}",
"Insert": "Insert",
"File": "File",
"Edit": "Edit",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help",
"Tools": "Tools",
"View": "View",
"Table": "Tabel",
"Format": "Format"
});